### ISSUE TITLE
Wrong translation in english abstract

### ISSUE THREAD

**Issue by DevxMike** [przemarbor/szablon_pracy_dyplomowej_weii#1]
https://github.com/przemarbor/szablon_pracy_dyplomowej_weii/blob/f750268d7e33e053573846f07c8c15771c588742/weiiszablon.sty#L417C1-L417C41

**Comment by przemarbor** [comment]
Corrected: https://github.com/przemarbor/szablon_pracy_dyplomowej_weii/commit/a10a43d428b4f7317f2585c260f32378ce1cd67d
